# Generated by Django 3.2.5 on 2021-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewform',
            name='candidate_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
