# Generated by Django 3.2.5 on 2021-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_interviewform_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewform',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
