# Generated by Django 3.2.5 on 2021-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_interviewform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewform',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
