# Generated by Django 3.2.5 on 2021-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_interviewform_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewform',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
